# List of all the containers that needs to be spun up.
# The workspace container will be added and configured automatically.
# The Syntax for each container should mimic the docker-compose format.
containers:
  nginx:
    image: '433610389961.dkr.ecr.us-west-2.amazonaws.com/nginx:latest'
    ports: [80]
    links: ['workspace']
    memory: 256
  workspace:
    memory: 2048

# Environment Variables to be injected in the container.
environment:
  nginx:
    web_docroot: '/srv/app/src/www'
    custom_config_file: '/srv/app/infra/nginx/sandbox.conf'
    server_name: ''
    domain_hash: ''
  workspace:
    encryption_sauce: 'WqNGjk@%ym7eRsXGAZYskF'

# All secondary domains are automatically setup as nginx aliases, and all of them are SSL-enabled by default.
domains:
  primary: '{project_name}-{instance_name}' # .e.tux.rocks

# Sequences for this environment.
sequences:

  install:
    Installing: '/srv/app/scripts/install.sh'
